export const photos = [
  {
    src: require("./imgs/normal/the-lovers-in-pandemic.jpg"),
    width: 4,
    height: 2,
    title: `"The lovers in pandemic"`,
  },
  {
    src: require("./imgs/normal/portrait-of-gala_salvador-dali.jpg"),
    width: 8,
    height: 8,
    title: `"Gala is a little different"`,
  },
  {
    src: require("./imgs/normal/prison.jpg"),
    width: 8,
    height: 8,
    title: `"Man is condemned to be free."`,
  },
  {
    src: require("./imgs/normal/ideas.jpg"),
    width: 5,
    height: 4,
    title: `"Create"`,
  },
  {
    src: require("./imgs/normal/up-tratada.jpg"),
    width: 5,
    height: 4,
    title: `"Work"`,
  },
  {
    src: require("./imgs/normal/mindless.jpg"),
    width: 5,
    height: 4,
    title: `"Mindless"`,
  },
  {
    src: require("./imgs/normal/pattern.jpg"),
    width: 3,
    height: 2,
    title: `"Pattern"`,
  },
  {
    src: require("./imgs/normal/swing.jpg"),
    width: 3,
    height: 2,
    title: `"Smile"`,
  },
  {
    src: require("./imgs/normal/bait.jpg"),
    width: 5,
    height: 4,
    title: `"Bait"`,
  },
  {
    src: require("./imgs/normal/escada-para-o-ceu.jpg"),
    width: 5,
    height: 4,
    title: `"Quanto maior a altura, maior a queda"`,
  },
  {
    src: require("./imgs/normal/olhar-alem-celular.jpg"),
    width: 4,
    height: 2,
    title: `"Olhar além do celular pode ser encantador"`,
  },
  {
    src: require("./imgs/normal/grade-gabriela.jpg"),
    width: 4,
    height: 2,
    title: `"Gabriela"`,
  },
  {
    src: require("./imgs/normal/dia-das-criancas.jpg"),
    width: 4,
    height: 3,
    title: `"Be the Child"`,
  },
  {
    src: require("./imgs/normal/de-volta-as-aulas-2.jpg"),
    width: 5,
    height: 3,
    title: `"De volta as aulas"`,
  },
  {
    src: require("./imgs/normal/ferias.jpg"),
    width: 6,
    height: 2,
    title: `"Férias"`,
  },
  {
    src: require("./imgs/normal/sem-cabeca.jpg"),
    width: 8,
    height: 8,
    title: `"Sem cabeça"`,
  },
  {
    src: require("./imgs/normal/uma-foto-sem-camera.jpg"),
    width: 8,
    height: 8,
    title: `"Uma foto sem a câmera?"`,
  },
  {
    src: require("./imgs/normal/florescer.jpg"),
    width: 8,
    height: 8,
    title: `"Florescer requer cuidados"`,
  },
  {
    src: require("./imgs/normal/de-volta-as-aulas.jpg"),
    width: 8,
    height: 3,
    title: `"De volta as aulas"`,
  },
  {
    src: require("./imgs/normal/pequeno-grande-homem.jpg"),
    width: 3,
    height: 2,
    title: `"Pequeno grande homem"`,
  },
  {
    src: require("./imgs/normal/o-jogo.jpg"),
    width: 6,
    height: 2,
    title: `"O jogo"`,
  },
  {
    src: require("./imgs/normal/minha-velha-amiga.jpg"),
    width: 5,
    height: 4,
    title: `"Minha velha amiga"`,
  },
  {
    src: require("./imgs/normal/dissera-para-eu-correr-atras-dos-meus-sonhos.jpg"),
    width: 5,
    height: 4,
    title: `"Disseram para eu correr atrás dos meus sonhos..."`,
  },
  {
    src: require("./imgs/normal/magica.png"),
    width: 4,
    height: 3,
    title: `"Magic"`,
  },
  {
    src: require("./imgs/normal/dia-amoroso.jpg"),
    width: 4,
    height: 2,
    title: `"Dia amoroso"`,
  },
  {
    src: require("./imgs/normal/barriga-negativa.jpg"),
    width: 4,
    height: 3,
    title: `"Barriga sarada"`,
  },
];
