export const photos = [
  {
    src: require("./imgs/mari.jpg"),
    width: 5,
    height: 4,
    title: `"Mari"`,
  },
  {
    src: require("./imgs/mari-2.jpg"),
    width: 5,
    height: 4,
    title: `"Mari"`,
  },
  {
    src: require("./imgs/mari-3.jpg"),
    width: 5,
    height: 4,
    title: `"Mari"`,
  },
  {
    src: require("./imgs/duda.jpg"),
    width: 8,
    height: 8,
    title: `"Duda"`,
  },
  {
    src: require("./imgs/duda-2.jpg"),
    width: 8,
    height: 8,
    title: `"Duda"`,
  },
  {
    src: require("./imgs/theus.jpg"),
    width: 8,
    height: 8,
    title: `"Theus"`,
  },
  {
    src: require("./imgs/theus-2.jpg"),
    width: 8,
    height: 8,
    title: `"Theus"`,
  },
  {
    src: require("./imgs/theus-3.jpg"),
    width: 4,
    height: 1,
    title: `"Theus"`,
  },
  {
    src: require("./imgs/duda-2.jpg"),
    width: 8,
    height: 8,
    title: `"Duda"`,
  },
  {
    src: require("./imgs/duda-3.jpg"),
    width: 8,
    height: 8,
    title: `"Duda"`,
  },
  {
    src: require("./imgs/duda-4.jpg"),
    width: 8,
    height: 8,
    title: `"Duda"`,
  },
  {
    src: require("./imgs/duda-5.jpg"),
    width: 8,
    height: 8,
    title: `"Duda"`,
  },
  {
    src: require("./imgs/gabriel.jpg"),
    width: 8,
    height: 8,
    title: `"Gabriel"`,
  },
  {
    src: require("./imgs/gabriel-2.jpg"),
    width: 8,
    height: 8,
    title: `"Gabriel"`,
  },
  {
    src: require("./imgs/gabriel-3.jpg"),
    width: 8,
    height: 8,
    title: `"Gabriel"`,
  },
  {
    src: require("./imgs/gabriel-4.jpg"),
    width: 8,
    height: 8,
    title: `"Gabriel"`,
  },
  {
    src: require("./imgs/jade.jpg"),
    width: 5,
    height: 4,
    title: `"Jade"`,
  },
  {
    src: require("./imgs/pequenas-muchachas.jpg"),
    width: 5,
    height: 4,
    title: `"Pequeñas Muchachas"`,
  },
  {
    src: require("./imgs/pequenas-muchachas-2.jpg"),
    width: 5,
    height: 4,
    title: `"Pequeñas Muchachas"`,
  },
  {
    src: require("./imgs/debora.jpg"),
    width: 5,
    height: 4,
    title: `"Débora"`,
  },
  {
    src: require("./imgs/debora-2.jpg"),
    width: 5,
    height: 4,
    title: `"Débora"`,
  },
  {
    src: require("./imgs/natan.jpg"),
    width: 5,
    height: 4,
    title: `"Natan"`,
  },
  {
    src: require("./imgs/gabriela.jpg"),
    width: 5,
    height: 5,
    title: `"Gabriela"`,
  },
  {
    src: require("./imgs/gabriela-2.jpg"),
    width: 5,
    height: 5,
    title: `"Gabriela"`,
  },
  {
    src: require("./imgs/gabriela-3.jpg"),
    width: 5,
    height: 5,
    title: `"Gabriela"`,
  },
];
